<?php

namespace FileBundle\Repository;

/**
 * FileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends \Doctrine\ORM\EntityRepository
{
    use \BaseBundle\Repository\BaseRepository;
    public function getByBnom1(\FileBundle\Entity\File $entity, $bNomKey = null) {
        $qb = $this->createQueryBuilder('f');
        $qb->select('f')
            ->join('f.bnomType1', 'bnom1')
            ->andWhere('f=:file')
            ->setParameter('file', $entity)
            ->andWhere('bnom1.bnomKey = :bkey1')
            ->setParameter('bkey1', $bNomKey)
        ;

        return $qb->getQuery()->getResult();
    }
}
