parameters:
    version: 3.1.102
    mailer_transport: smtp

    base_airport: LBLS
    sender_name: FMS
    mailer_transport: smtp
    mailer_host: gmail.com
    mailer_user: 'dnkadir@gmail.com'
    mailer_password: 'RnIv9k6#7DeF'
    mail_sender: 'dnkadir@gmail.com'
    mail_bug_report: 'dnkadir@gmail.com'
    default_country: BG
    bookingCourseName: 'PPL(A)'
    captcha:
        'What is the capital of Bulgaria?': 'sofia'
        'What is the capital of Canada?': 'ottawa'
        'What is the capital of –êustralia?': 'canberra'
        'What is the longest river in the world?': 'nile'
        'What is the highest peak in Bulgaria?': 'musala'

    upload_directory: '%kernel.project_dir%/var/uploads'

    i18n:
        date_format: dd.mm.yyyy
        date_format_s: d.m.Y
        time_format: HH:MM
        date_time_format: dd.mm.yyyy HH:MM
        date_time_format_s: d.m.Y H:i
        date_time_format_js: dd.mm.yyyy hh:ii
        timepick_format: 'H:i'
        timepick_disable:
            - '12:00'
            - '13:00'
    date_format_validation: (0?[1-9]|[12][0-9]|3[01])\.(0?[1-9]|1[012])\.[0-9]{4}
    time_format_validation: ^(0[0-9]|1[0-9]|2[0-3]):([0-5][0-9])

    max_waiting_books: 300
    message_send_interval:
        booking: 1000 #seconds
        license: 604800 #seconds 7*24*60*60
        license_lpc: 604800 #seconds 7*24*60*60
        license_opc: 604800 #seconds 7*24*60*60
        medical_license: 864000 #seconds 10*24*60*60
        license_endorsement: 604800 #seconds 7*24*60*60

    template_variables:
        0: username
        1: from
        2: to
        3: url
    upload_directory: '%kernel.project_dir%/var/uploads'
    empty_avatar_url: '/images/no_avatar.png'
    hide_session_selector_from_flight_form: false

twig:
    globals:
        _layout: 'layout_default.html.twig'
        javascript_urls:
            admin: ['basenom_list', 'basenom_add_new', 'basenom_add', 'basenom_reorder', 'loadNomTree',  'getNomType']
            user: []
            all: ['basenom_get_list', 'basenom_load_child', 'basenom_load_child1',  'ReadNomList', 'getNomType1', 'profile_last_flight', 'fos_user_security_logout']
