<?php

namespace WorkPlaceBundle\Repository;

/**
 * WorkPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
