<?php

namespace UsersBundle\Repository;

/**
 * InstitutionEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstitutionEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
     use \BaseBundle\Repository\BaseRepository;
}
