<?php

namespace BaseBundle\Repository;

/**
 * BaseNomsExtraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseNomsExtraRepository extends \Doctrine\ORM\EntityRepository
{
	use \BaseBundle\Repository\BaseRepository;
}
