<?php

namespace BaseBundle\Repository;

/**
 * EduInstitutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EduInstitutionRepository extends \Doctrine\ORM\EntityRepository
{
    use \BaseBundle\Repository\BaseRepository;

    function findInstitution($filter, $returnQueryBuilder = false, $order = []) {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u');
        
        if (!empty($filter['name'])) {
            $qb->leftJoin('u.region', 'r')
                ->leftJoin('u.place', 'p');
            $qb->andWhere($qb->expr()->orX(
                $qb->expr()->like('u.name', ':name'),
                //$qb->expr()->like('r.name', ':name'),
                $qb->expr()->like('p.name', ':name')
            ))->setParameter('name', '%'.$filter['name'].'%');
            $qb->addOrderBy('u.name', 'ASC');

        }

        if (!empty($order)) {
            foreach($order as $col => $orderType) {
                $qb->addOrderBy('u.'.$col, $orderType);    
            }
            
        }
        return $returnQueryBuilder ? $qb : $qb->getQuery()->getResult();
    }
}
